apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      labels:
        io.kompose.service: web
    spec:
      containers:
        - image: fast2_test
          imagePullPolicy: IfNotPresent
          name: web
          ports:
            - containerPort: 8000
      restartPolicy: Always


