apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
    - name: web
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: web
